global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'ui'
    metrics_path: '/metrics/application'
    scrape_interval: 5s
    static_configs:
      - targets: ['ui:8080']
  - job_name: 'server'
    metrics_path: '/metrics/application'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'server:8080' ]